CREATE TABLE IF NOT EXISTS factory_projects (
  id INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  factory_project_id VARCHAR(40) NOT NULL,
  client_id BIGINT UNSIGNED NULL,
  source VARCHAR(40) NOT NULL DEFAULT 'admin',
  site_slug VARCHAR(120) NULL,
  site_lang VARCHAR(20) NOT NULL DEFAULT 'zh-TW',
  site_title VARCHAR(190) NULL,
  site_description TEXT NULL,
  favicon_path VARCHAR(255) NULL,
  theme_id VARCHAR(80) NULL,
  business_type VARCHAR(120) NULL,
  project_status VARCHAR(40) NOT NULL DEFAULT '草稿',
  factory_status VARCHAR(40) NOT NULL DEFAULT 'draft',
  current_revision_id INT(10) UNSIGNED NULL,
  published_url TEXT NULL,
  published_at DATETIME NULL,
  expires_at DATETIME NULL,
  created_at DATETIME NOT NULL,
  updated_at DATETIME NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uq_factory_projects_project_id (factory_project_id),
  KEY idx_factory_projects_client_id (client_id),
  KEY idx_factory_projects_site_slug (site_slug),
  KEY idx_factory_projects_status (factory_status),
  KEY idx_factory_projects_expires_at (expires_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS factory_project_profiles (
  id INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  factory_project_id VARCHAR(40) NOT NULL,
  brand_name VARCHAR(190) NULL,
  tagline VARCHAR(190) NULL,
  description TEXT NULL,
  address VARCHAR(255) NULL,
  phone VARCHAR(40) NULL,
  email VARCHAR(190) NULL,
  line_url TEXT NULL,
  google_map_embed_url TEXT NULL,
  raw_profile_json LONGTEXT NULL,
  created_at DATETIME NOT NULL,
  updated_at DATETIME NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uq_factory_project_profiles_project_id (factory_project_id),
  KEY idx_factory_project_profiles_brand_name (brand_name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS factory_site_revisions (
  id INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  factory_project_id VARCHAR(40) NOT NULL,
  revision_no INT(10) UNSIGNED NOT NULL DEFAULT 1,
  revision_status VARCHAR(40) NOT NULL DEFAULT 'draft',
  source VARCHAR(40) NOT NULL DEFAULT 'admin',
  site_config_json LONGTEXT NULL,
  created_by VARCHAR(120) NULL,
  created_at DATETIME NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uq_factory_site_revisions_project_revision (factory_project_id, revision_no),
  KEY idx_factory_site_revisions_project_id (factory_project_id),
  KEY idx_factory_site_revisions_status (revision_status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS factory_page_blocks (
  id INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  factory_project_id VARCHAR(40) NOT NULL,
  revision_id INT(10) UNSIGNED NOT NULL,
  block_key VARCHAR(80) NOT NULL,
  block_type VARCHAR(80) NOT NULL,
  variant VARCHAR(40) NULL,
  sort_order INT(10) UNSIGNED NOT NULL DEFAULT 0,
  is_enabled TINYINT(1) NOT NULL DEFAULT 1,
  block_data_json LONGTEXT NULL,
  created_at DATETIME NOT NULL,
  updated_at DATETIME NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uq_factory_page_blocks_revision_key (revision_id, block_key),
  KEY idx_factory_page_blocks_project_revision_order (factory_project_id, revision_id, sort_order),
  KEY idx_factory_page_blocks_type (block_type),
  KEY idx_factory_page_blocks_enabled (is_enabled)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS factory_assets (
  id INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  factory_project_id VARCHAR(40) NOT NULL,
  asset_type VARCHAR(40) NOT NULL DEFAULT 'other',
  original_name VARCHAR(190) NULL,
  file_path TEXT NULL,
  public_url TEXT NULL,
  mime_type VARCHAR(80) NULL,
  file_size INT(10) UNSIGNED NULL,
  width INT(10) UNSIGNED NULL,
  height INT(10) UNSIGNED NULL,
  sort_order INT(10) UNSIGNED NOT NULL DEFAULT 0,
  created_at DATETIME NOT NULL,
  PRIMARY KEY (id),
  KEY idx_factory_assets_project_id (factory_project_id),
  KEY idx_factory_assets_type (asset_type),
  KEY idx_factory_assets_sort_order (sort_order)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS factory_inquiries (
  id INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  factory_project_id VARCHAR(40) NULL,
  client_id BIGINT UNSIGNED NULL,
  source VARCHAR(40) NOT NULL DEFAULT 'booking_form',
  name VARCHAR(120) NOT NULL,
  phone VARCHAR(40) NOT NULL,
  email VARCHAR(190) NULL,
  website_type VARCHAR(120) NULL,
  budget_range VARCHAR(80) NULL,
  message TEXT NULL,
  inquiry_status VARCHAR(40) NOT NULL DEFAULT 'new',
  ip_address VARCHAR(45) NULL,
  user_agent TEXT NULL,
  raw_payload LONGTEXT NULL,
  created_at DATETIME NOT NULL,
  updated_at DATETIME NOT NULL,
  PRIMARY KEY (id),
  KEY idx_factory_inquiries_project_id (factory_project_id),
  KEY idx_factory_inquiries_client_id (client_id),
  KEY idx_factory_inquiries_phone (phone),
  KEY idx_factory_inquiries_status (inquiry_status),
  KEY idx_factory_inquiries_created_at (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS factory_exports (
  id INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  factory_project_id VARCHAR(40) NOT NULL,
  revision_id INT(10) UNSIGNED NULL,
  export_type VARCHAR(40) NOT NULL DEFAULT 'preview',
  export_status VARCHAR(40) NOT NULL DEFAULT 'pending',
  output_path TEXT NULL,
  public_url TEXT NULL,
  download_token CHAR(64) NULL,
  expires_at DATETIME NULL,
  error_code VARCHAR(80) NULL,
  error_message TEXT NULL,
  created_at DATETIME NOT NULL,
  updated_at DATETIME NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uq_factory_exports_download_token (download_token),
  KEY idx_factory_exports_project_id (factory_project_id),
  KEY idx_factory_exports_revision_id (revision_id),
  KEY idx_factory_exports_status (export_status),
  KEY idx_factory_exports_expires_at (expires_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
